version: '3'

tasks:
  plan:
    desc: Run terragrunt plan
    dir: examples/terragrunt
    cmds:
      - terragrunt plan

  apply:
    desc: Run terragrunt apply
    dir: examples/terragrunt
    cmds:
      - terragrunt apply -auto-approve

  fmt:
    desc: Format terraform files
    dir: src/
    cmds:
      - tofu fmt -recursive

  check-llm:
    desc: Run concise terragrunt plan optimized for machines / LLM
    dir: examples/terragrunt
    cmds:
      - terragrunt validate && terragrunt plan -json | grep -v '"@level":"info"'